# Register the context-manager MCP server as a boot-persistent "service" on the
# dev machine — a Scheduled Task (AtStartup, SYSTEM, restart-on-failure, no time
# limit) rather than an SCM service, so it needs no third-party wrapper (NSSM).
#
# Run elevated (or via `sudo`):
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\setup_service.ps1
#
# Idempotent: re-running replaces the task, launcher, and firewall rule in place.
# The task action is a generated launcher (<CtxDir>\run-server.cmd) because a
# scheduled task cannot set env vars itself; the launcher also rotates the log.

#Requires -RunAsAdministrator
[CmdletBinding()]
param(
    # console script installed by the wheel; auto-detected if not given
    [string]$ServerExe = "",
    # NOT named -Db: CmdletBinding's -Debug owns the alias "db"
    [string]$DbPath = "D:\ctx\team.db",
    [int]$Port = 8765,
    [string]$BindHost = "0.0.0.0",          # 0.0.0.0 = reachable over the LAN
    [string]$TaskName = "context-manager-mcp",
    [string]$CtxDir = "D:\ctx",
    [switch]$NoFirewall                      # skip the LAN inbound allow rule
)

$ErrorActionPreference = "Stop"

# --- locate the server exe ---------------------------------------------------
if (-not $ServerExe) {
    $cmd = Get-Command ctx-mcp-server -ErrorAction SilentlyContinue
    if ($cmd) { $ServerExe = $cmd.Source }
    else {
        $guess = "D:\2files\env_build\conda\conda\envs\ctx_env\Scripts\ctx-mcp-server.exe"
        if (Test-Path $guess) { $ServerExe = $guess }
    }
}
if (-not $ServerExe -or -not (Test-Path $ServerExe)) {
    throw "ctx-mcp-server.exe not found - pip install the wheel first, or pass -ServerExe"
}
Write-Host "server exe : $ServerExe"
Write-Host "team DB    : $DbPath  (this file IS the team's memory - back it up)"

New-Item -ItemType Directory -Force $CtxDir | Out-Null
$log = Join-Path $CtxDir "server.log"
$launcher = Join-Path $CtxDir "run-server.cmd"

# --- generated launcher: env vars + 10MB log rotation + attached launch ------
# (stays attached so a server crash fails the task and triggers the restart policy)
@"
@echo off
rem generated by setup_service.ps1 - do not edit; re-run the setup to change
set CTX_DB=$DbPath
set CTX_HOST=$BindHost
set CTX_PORT=$Port
if exist "$log" for %%A in ("$log") do if %%~zA GTR 10485760 move /y "$log" "$log.1" >nul
"$ServerExe" >> "$log" 2>&1
"@ | Set-Content -Path $launcher -Encoding ascii
Write-Host "launcher   : $launcher"

# --- stop whatever currently owns the port (only if it looks like ours) ------
$listeners = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
             Select-Object -ExpandProperty OwningProcess -Unique
foreach ($lpid in $listeners) {
    $proc = Get-Process -Id $lpid -ErrorAction SilentlyContinue
    if (-not $proc) { continue }
    if ($proc.ProcessName -notin @("ctx-mcp-server", "python", "pythonw")) {
        throw "port $Port is held by '$($proc.ProcessName)' (pid $lpid) - not ours, aborting"
    }
    Write-Host "stopping existing server: $($proc.ProcessName) (pid $lpid)"
    Stop-Process -Id $lpid -Force -Confirm:$false
}
Get-Process ctx-mcp-server -ErrorAction SilentlyContinue |
    Stop-Process -Force -Confirm:$false -ErrorAction SilentlyContinue

# --- register the task (replace if it exists) --------------------------------
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}
$action    = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c `"$launcher`""
$trigger   = New-ScheduledTaskTrigger -AtStartup
$principal = New-ScheduledTaskPrincipal -UserId "NT AUTHORITY\SYSTEM" `
                 -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
                 -StartWhenAvailable -MultipleInstances IgnoreNew `
                 -RestartCount 10 -RestartInterval (New-TimeSpan -Minutes 1) `
                 -ExecutionTimeLimit ([TimeSpan]::Zero)
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings | Out-Null
Write-Host "task       : $TaskName (AtStartup, SYSTEM, restart x10 on failure, no time limit)"

# --- firewall: let the other box reach it over the LAN -----------------------
if (-not $NoFirewall) {
    $ruleName = "context-manager MCP $Port"
    Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue |
        Remove-NetFirewallRule
    New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Protocol TCP `
        -LocalPort $Port -Action Allow -Profile Domain, Private | Out-Null
    Write-Host "firewall   : inbound TCP $Port allowed (Domain+Private profiles)"
}

# --- start now and health-check ----------------------------------------------
Start-ScheduledTask -TaskName $TaskName
$up = $false
foreach ($i in 1..30) {
    Start-Sleep -Milliseconds 500
    try {
        $c = [System.Net.Sockets.TcpClient]::new()
        $c.Connect("127.0.0.1", $Port); $c.Close(); $up = $true; break
    } catch {}
}
if (-not $up) {
    Write-Host "`nSERVER DID NOT COME UP - last log lines:" -ForegroundColor Red
    if (Test-Path $log) { Get-Content $log -Tail 20 }
    exit 1
}
Write-Host "`nOK - serving on http://127.0.0.1:$Port/mcp (state: $((Get-ScheduledTask -TaskName $TaskName).State))"
Write-Host "log: $log"
Write-Host "add on each box: claude mcp add --transport http --scope user context-manager http://<this-machine-ip>:$Port/mcp"
